run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - gofumpt
    - gofmt
    - gosimple
    - gocritic
    - staticcheck
    - ineffassign
    - revive
    - misspell

linters-settings:
  gofmt:
    simplify: true
  gofumpt:
    extra-rules: true
  gocritic:
    enabled-checks:
      - appendAssign
      - ifElseChain
      - sloppyLen
      - boolExprSimplify
  revive:
    rules:
      - name: indent-error-flow
      - name: early-return
      - name: package-comments

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/httpapi/handlers
      linters:
        - revive
